In [ ]:
import numpy as np
#creating 1D,2D,3D arrays
a=np.array([10,4,5])
print(a)
b=np.array([[12,4,5]])
print(b)
c=np.array([[[2,4,6]]])
print(c)
d=np.array([[1,4,6],[4,6,7]])
print(d)
e=np.array([[[10]]])
print(e)
f=np.array([[[[22,4,5],[4,5,6],[6,6,7]]]])
print(f)



[10  4  5]
[[12  4  5]]
[[[2 4 6]]]
[[1 4 6]
 [4 6 7]]
[[[10]]]
[[[[22  4  5]
   [ 4  5  6]
   [ 6  6  7]]]]


In [ ]:
a=np.array(['25','5.6',"hi",True])
print(a)
n=np.array([[2,3,4],[6,6,7]])
print(n)
g=np.zeros(6)
print(g)
k=np.zeros((6,5),dtype=int)
print(k)
l=np.ones(3)
print(l)
p=np.ones((2,1),dtype=int)
print(p)
d=np.empty((2,1),dtype=int)
print(d)
s=np.arange(4)
print(s)
t=np.arange(1,6,2)
print(t)

['25' '5.6' 'hi' 'True']
[[2 3 4]
 [6 6 7]]
[0. 0. 0. 0. 0. 0.]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[1. 1. 1.]
[[1]
 [1]]
[[           1]
 [206158430208]]
[0 1 2 3]
[1 3 5]


In [ ]:
import numpy as np
a=np.eye(3,4,k=2)
print(a)
i=np.identity(4)
print(i)
w=np.full((4,5),'ammu')
print(w)
l=np.random.seed(10)
print(l)
u=np.random.rand(4,3)
print(u)
o=np.random.randint(3,7,(4,5))
print(o)
e=np.array([[2,3,4],[4,5,6]])
print(e)
print(e.shape)
print(e.size)
print(e.ndim)
print(e.dtype)
print(e.itemsize)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[['ammu' 'ammu' 'ammu' 'ammu' 'ammu']
 ['ammu' 'ammu' 'ammu' 'ammu' 'ammu']
 ['ammu' 'ammu' 'ammu' 'ammu' 'ammu']
 ['ammu' 'ammu' 'ammu' 'ammu' 'ammu']]
None
[[0.77132064 0.02075195 0.63364823]
 [0.74880388 0.49850701 0.22479665]
 [0.19806286 0.76053071 0.16911084]
 [0.08833981 0.68535982 0.95339335]]
[[6 6 5 3 6]
 [5 5 4 3 3]
 [5 4 6 5 4]
 [4 4 6 4 5]]
[[2 3 4]
 [4 5 6]]
(2, 3)
6
2
int64
8
