In [ ]:
import torch as torch


In [ ]:
#pytorch is used in deep learning,c.v,n.l.p,
#torch is function use in pytorch
import torch as torch
a=torch.tensor(3)
print(a)
print(a.shape)
b=torch.tensor([3,5,7,8])
print(b)
print(b.shape)
print(b.size())
c=torch.tensor([[1,2,3,4],[4,6,7,8]])
print(c)
print(c.shape)
print(c.size())#no.of rows and columns
print(c.numel())#no.of elements
print(torch.zeros((3,3)))
print(torch.zeros([3,3]))
print(torch.ones((3,3)))
print(torch.ones([3,3]))
print(torch.full((3,3),514))
#print(torch.full((3,3),'a'))does'nt support string
print(torch.arange(2,35,8))
print(c.dtype)
print(torch.rand(3,3))
print(torch.rand(1))
print(torch.rand(4,5,2))
print(torch.randn(3,3))#mixed random values
d=torch.tensor([[1,8,4],[1,9,16]])


tensor(3)
torch.Size([])
tensor([3, 5, 7, 8])
torch.Size([4])
torch.Size([4])
tensor([[1, 2, 3, 4],
        [4, 6, 7, 8]])
torch.Size([2, 4])
torch.Size([2, 4])
8
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[514, 514, 514],
        [514, 514, 514],
        [514, 514, 514]])
tensor([ 2, 10, 18, 26, 34])
torch.int64
tensor([[0.8623, 0.0713, 0.3029],
        [0.7978, 0.3274, 0.3690],
        [0.4366, 0.4215, 0.6696]])
tensor([0.9974])
tensor([[[8.6043e-01, 1.4837e-01],
         [7.5107e-01, 7.1198e-01],
         [3.1346e-01, 4.6631e-01],
         [3.6956e-01, 6.4817e-01],
         [3.2078e-01, 7.3180e-01]],

        [[9.0888e-01, 6.3926e-04],
         [4.0326e-01, 8.3734e-01],
         [4.6617e-01, 4.2042e-01],
         [9.0998e-01, 9.2215e-01],
         [2.987

In [8]:
import torch
a=torch.tensor([[13,36,39],[4,8,12]])
print(a)
print(a.ndim)
print(a.shape)
print(a.numel())
print(a.dtype)
print(a.device)

tensor([[13, 36, 39],
        [ 4,  8, 12]])
2
torch.Size([2, 3])
6
torch.int64
cpu


In [14]:
print(torch.ones((2,3),dtype=int))
print(torch.ones((2,3),dtype=torch.int32))

tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [17]:
print(torch.rand(2,4))
print(torch.randn(2,4))

tensor([[0.8289, 0.7410, 0.4426, 0.2869],
        [0.1327, 0.7560, 0.9758, 0.2615]])
tensor([[ 1.5613, -1.6864,  2.5302,  0.4307],
        [ 1.9452,  0.5132,  0.7058,  0.9486]])


In [22]:
#indexing
h=torch.tensor([[10,12,13],[14,15,16],[17,18,19]])
print(h[1])
print(h[2])
print(h[[1,2]])
print(h[[1,2],1])
print(h[[0,1,2]])
print(h[[0,1,2],2])

tensor([14, 15, 16])
tensor([17, 18, 19])
tensor([[14, 15, 16],
        [17, 18, 19]])
tensor([15, 18])
tensor([[10, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])
tensor([13, 16, 19])


In [25]:
#slicing
print(h[0:3,0:1])
print(h[:3,0])
print(h[:,0])
print(h[:,0:1])

tensor([[10],
        [14],
        [17]])
tensor([10, 14, 17])
tensor([10, 14, 17])
tensor([[10],
        [14],
        [17]])
tensor([[17, 18, 19]])


In [26]:
print(h[2:3,0:3])
print(h[2:3,:3])
print(h[2:,:3])
print(h[2:3,:])


tensor([[17, 18, 19]])
tensor([[17, 18, 19]])
tensor([[17, 18, 19]])
tensor([[17, 18, 19]])


In [30]:
f=torch.tensor([[2,8,10],[4,5,6],[10,11,12]])
print(torch.sum(f))
print(f.sum())

tensor(68)
tensor(68)


In [34]:
l=torch.tensor([[2,8,10],[4,5,6],[10,11,12]])
m=torch.tensor([[10,12,13],[14,15,16],[17,18,19]])
print(torch.subtract(l,m))
print(torch.mul(l,m))
print(torch.divide(l,m))

tensor([[ -8,  -4,  -3],
        [-10, -10, -10],
        [ -7,  -7,  -7]])
tensor([[ 20,  96, 130],
        [ 56,  75,  96],
        [170, 198, 228]])
tensor([[0.2000, 0.6667, 0.7692],
        [0.2857, 0.3333, 0.3750],
        [0.5882, 0.6111, 0.6316]])


In [39]:
print(l.max())
print(l.min())
print(l.argmax())

tensor(12)
tensor(2)
tensor(8)


In [44]:
#boolean indexing
v=torch.tensor([70,36,27,50,99])
print(v>50)
print([v[v>50]])

tensor([ True, False, False, False,  True])
[tensor([70, 99])]


In [46]:
print(v[v>34])
print(v[v<50])

tensor([70, 36, 50, 99])
tensor([36, 27])
