In [ ]:
import torch
a=torch.tensor([6,18,24])
b=torch.tensor([[10,15,18],[20,21,22]])
print(a)
print(b)
print(b.shape)#attribute
print(b.size())#funtion
print(b.ndim)#dimension
c=torch.tensor([99.,96,54])
print(c)
print(c.dtype)
d=torch.full((3,5),7)
print(d)
e=torch.empty(6)
print(e)
f=torch.zeros(1,4)
print(f)
g=torch.ones(1,2)
print(g)
h=torch.range(96,108)
print(h)
i=torch.range(96,108,6)
print(i)
j=torch.eye(3)
print(j)

tensor([ 6, 18, 24])
tensor([[10, 15, 18],
        [20, 21, 22]])
torch.Size([2, 3])
torch.Size([2, 3])
2
tensor([99., 96., 54.])
torch.float32
tensor([[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]])
tensor([-3.6763e-25,  4.5406e-41,  2.4112e-04,  0.0000e+00,  4.4842e-44,
         0.0000e+00])
tensor([[0., 0., 0., 0.]])
tensor([[1., 1.]])
tensor([ 96.,  97.,  98.,  99., 100., 101., 102., 103., 104., 105., 106., 107.,
        108.])
tensor([ 96., 102., 108.])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


/tmp/ipykernel_842/1575835948.py:20: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  h=torch.range(96,108)
/tmp/ipykernel_842/1575835948.py:22: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  i=torch.range(96,108,6)


In [ ]:
import torch#indexing
a=torch.tensor([514,560,588,720])
print(a)
print(a[2])
print(a[1:4])
print(a[:])
print(a[-3])
print(a.numel())



tensor([514, 560, 588, 720])
tensor(588)
tensor([560, 588, 720])
tensor([514, 560, 588, 720])
tensor(560)
4


In [ ]:
import torch
a=torch.tensor([19,36,45,69])
b=torch.tensor([[10,15,18],[20,21,22]])
c=torch.tensor([[[10,15,18,4,5],[20,21,22,7,8]],[[2,4,6,7,8],[1,3,4,5,6]],[[1,2,3,4,5],[1,5,6,7,8]]])
print(a)
print(c.shape)

tensor([19, 36, 45, 69])
torch.Size([3, 2, 5])


In [ ]:
import torch
a=torch.tensor([[6,15,21],[4,3,1]])
print(a)
print(a[1,1])#indexing
print(a[1:2,1:2])#slicing
print(a[1:3,2:3])
#concatenation
b=torch.tensor([[1,2],[3,4],[5,6]])
c=torch.tensor([[18,7],[8,9],[10,11]])
print(torch.cat((b,c),dim=1))#column concatenation
print(torch.cat((b,c),dim=0))#row concatenation
d=torch.tensor([[[2,3,4],[5,6,7],[1,2,4]]])
e=torch.tensor([[[6,7,8],[8,6,9],[0,7,8]]])
print(torch.cat((d,e),dim=1))
print(torch.cat((d,e),dim=0))
f=torch.tensor([[1,9],[2,5],[4,6]])
g=torch.tensor([[1,8,9],[5,7,6],[6,8,6]])
print(torch.cat((f,g),dim=1))
#print(torch.cat((f,g),dim=0))
h=torch.tensor([[1,9],[2,5],[4,6]])
i=torch.tensor([[1,8],[5,6]])
print(torch.cat((h,i),dim=0))
#splitting
j=torch.tensor([1,10,11,12,15,16])
print(torch.split(j,2))
k=torch.arange(20)
print(torch.split(k,4))
print(torch.split(k,[3,7,5,4,1]))
#chunk
print(torch.chunk(h,3))
#zeros
l=torch.zeros(4,5,6)
print(l)
print(l.size(1))
m=torch.ones(4,5,6)
print(m)
print(m.size(2))

tensor([[ 6, 15, 21],
        [ 4,  3,  1]])
tensor(3)
tensor([[3]])
tensor([[1]])
tensor([[ 1,  2, 18,  7],
        [ 3,  4,  8,  9],
        [ 5,  6, 10, 11]])
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [18,  7],
        [ 8,  9],
        [10, 11]])
tensor([[[2, 3, 4],
         [5, 6, 7],
         [1, 2, 4],
         [6, 7, 8],
         [8, 6, 9],
         [0, 7, 8]]])
tensor([[[2, 3, 4],
         [5, 6, 7],
         [1, 2, 4]],

        [[6, 7, 8],
         [8, 6, 9],
         [0, 7, 8]]])
tensor([[1, 9, 1, 8, 9],
        [2, 5, 5, 7, 6],
        [4, 6, 6, 8, 6]])
tensor([[1, 9],
        [2, 5],
        [4, 6],
        [1, 8],
        [5, 6]])
(tensor([ 1, 10]), tensor([11, 12]), tensor([15, 16]))
(tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]), tensor([ 8,  9, 10, 11]), tensor([12, 13, 14, 15]), tensor([16, 17, 18, 19]))
(tensor([0, 1, 2]), tensor([3, 4, 5, 6, 7, 8, 9]), tensor([10, 11, 12, 13, 14]), tensor([15, 16, 17, 18]), tensor([19]))
(tensor([[1, 9]]), tensor([

In [ ]:
import torch
b=torch.tensor([1,2,3,4])
print(b.device)
torch.cuda.is_available()

cpu


False