In [ ]:
import tensorflow
tensorflow.__version__

'2.20.0'

In [ ]:
import tensorflow as tf
a=tf.constant(8)
print("\n",a)


 tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
import tensorflow as tf
b=tf.Variable(9)
print("\n",b)



 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=9>


In [ ]:
c=tf.constant([[3,6,9],[7,10,11]])
print(c)
d=tf.Variable([[3,6,9],[7,10,11]])
print(d)
e=d.assign([[1,2,3],[4,5,6]])#variable can be modify by using assign
print(e)
#f=tf.constant([[3,6,9],[7,10,11]])constant cannot be modify
#g=f.assign([[1,2,3],[4,5,6]])
#print(g)


tf.Tensor(
[[ 3  6  9]
 [ 7 10 11]], shape=(2, 3), dtype=int32)
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 3,  6,  9],
       [ 7, 10, 11]], dtype=int32)>
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>


In [ ]:
h=tf.constant(7)
i=tf.constant([[1,4,6],[3,6,7]])
j=tf.constant([[[1,2,3],[3,5,6]]])
print(h)
print(i)
print(j)
print(tf.range(3,16,3))
print(tf.fill((3,3),8))

tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(
[[1 4 6]
 [3 6 7]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[1 2 3]
  [3 5 6]]], shape=(1, 2, 3), dtype=int32)
tf.Tensor([ 3  6  9 12 15], shape=(5,), dtype=int32)
tf.Tensor(
[[8 8 8]
 [8 8 8]
 [8 8 8]], shape=(3, 3), dtype=int32)


In [ ]:
print(tf.zeros((2,3)))
print(tf.zeros((6)))
print(tf.zeros((2,3,4)))

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor([0. 0. 0. 0. 0. 0.], shape=(6,), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(2, 3, 4), dtype=float32)


In [ ]:
v=tf.constant([[1,8,6],[1,10,1]])
print(v)
print(v.shape)
print(v.ndim)
print(v.dtype)
print(tf.size(v))

tf.Tensor(
[[ 1  8  6]
 [ 1 10  1]], shape=(2, 3), dtype=int32)
(2, 3)
2
<dtype: 'int32'>
tf.Tensor(6, shape=(), dtype=int32)


In [ ]:
j=tf.constant([[1,2,3],[3,5,6],[4,5,6]])#indexing
print(j[1,1])
print(j[1][1])
print(j[1])
print(j[2])
h=tf.transpose(j)
print(h[0])
i=tf.constant([[0,1,5,6],[1,5,4,3],[1,2,4,6]])
print(i)
k=tf.transpose(i)
print(k[2])
#indexing
print(k[2:3,0:4])
print(k[2:3])
print(i[2:4])
print(i[1:2,2:3])
print(i[1:3,2:4])
print(i[0:2,1:3])
print(i[-1,-3])
print(i[-1:-2:-1,-3:-4:-1])
print(i[-1:,-3])
l=tf.constant([2,6,8,0,3])
print(tf.reverse(l,axis=[0]))

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([3 5 6], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)
tf.Tensor([1 3 4], shape=(3,), dtype=int32)
tf.Tensor(
[[0 1 5 6]
 [1 5 4 3]
 [1 2 4 6]], shape=(3, 4), dtype=int32)
tf.Tensor([5 4 4], shape=(3,), dtype=int32)
tf.Tensor([[5 4 4]], shape=(1, 3), dtype=int32)
tf.Tensor([[5 4 4]], shape=(1, 3), dtype=int32)
tf.Tensor([[1 2 4 6]], shape=(1, 4), dtype=int32)
tf.Tensor([[4]], shape=(1, 1), dtype=int32)
tf.Tensor(
[[4 3]
 [4 6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 5]
 [5 4]], shape=(2, 2), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([[2]], shape=(1, 1), dtype=int32)
tf.Tensor([2], shape=(1,), dtype=int32)
tf.Tensor([3 0 8 6 2], shape=(5,), dtype=int32)


In [ ]:
#slicing
l=tf.constant([[2,6,8,0,3],[4,5,7,8,6]])
print(tf.reverse(l,axis=[0]))
print(tf.reverse(l,axis=[1]))
print(tf.reverse(l,axis=[1,0]))
print(tf.reverse(l,axis=[0,1]))
p=tf.constant([2,6,8,0])
q=tf.constant([9,5,7,4])
b=tf.reshape(p,(1,4))
print(b)
print(p.shape)
o=tf.reshape(p,(1,-1))
print(o)
x=tf.reshape(l,[-1])
print(x)
m=tf.add(p,q)
print(m)
print(tf.subtract(p,q))
print(tf.multiply(p,q))
print(tf.divide(p,q))

tf.Tensor(
[[4 5 7 8 6]
 [2 6 8 0 3]], shape=(2, 5), dtype=int32)
tf.Tensor(
[[3 0 8 6 2]
 [6 8 7 5 4]], shape=(2, 5), dtype=int32)
tf.Tensor(
[[6 8 7 5 4]
 [3 0 8 6 2]], shape=(2, 5), dtype=int32)
tf.Tensor(
[[6 8 7 5 4]
 [3 0 8 6 2]], shape=(2, 5), dtype=int32)
tf.Tensor([[2 6 8 0]], shape=(1, 4), dtype=int32)
(4,)
tf.Tensor([[2 6 8 0]], shape=(1, 4), dtype=int32)
tf.Tensor([2 6 8 0 3 4 5 7 8 6], shape=(10,), dtype=int32)
tf.Tensor([11 11 15  4], shape=(4,), dtype=int32)
tf.Tensor([-7  1  1 -4], shape=(4,), dtype=int32)
tf.Tensor([18 30 56  0], shape=(4,), dtype=int32)
tf.Tensor([0.22222222 1.2        1.14285714 0.        ], shape=(4,), dtype=float64)


In [ ]:
import tensorflow as tf
b=tf.constant([[3,4],[5,6],[7,8]])
print(tf.reduce_mean(b))
print(tf.reduce_sum(b))
print(tf.reduce_max(b))
print(tf.reduce_min(b))
print(tf.reduce_mean(b,axis=0))
print(tf.reduce_sum(b,axis=0))
print(tf.reduce_max(b,axis=0))
print(tf.reduce_min(b,axis=0))
print(tf.reduce_mean(b,axis=1))
print(tf.reduce_sum(b,axis=1))
print(tf.reduce_max(b,axis=1))
print(tf.reduce_min(b,axis=1))

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(33, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([5 6], shape=(2,), dtype=int32)
tf.Tensor([15 18], shape=(2,), dtype=int32)
tf.Tensor([7 8], shape=(2,), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)
tf.Tensor([3 5 7], shape=(3,), dtype=int32)
tf.Tensor([ 7 11 15], shape=(3,), dtype=int32)
tf.Tensor([4 6 8], shape=(3,), dtype=int32)
tf.Tensor([3 5 7], shape=(3,), dtype=int32)
